---
Name: base-mysql
After: '#databaseconnectors'
---
# Because there is really no reason to use regular utf8
SilverStripe\ORM\Connect\MySQLDatabase:
  connection_charset: utf8mb4
  connection_collation: utf8mb4_unicode_ci
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
# You also have to be aware that if you set an index on a big char or varchar field
# which is utf8mb4 encoded, you have to divide the max index prefix length of 767 bytes (or 3072 bytes) by 4
# resulting in 191. This is because the maximum length of a utf8mb4 character is four bytes.
# For a utf8 character it would be three bytes resulting in max index prefix length of 254.
