---
Name: base-dev
Only:
  environment: dev
---
SilverStripe\Control\Director:
  rules:
    'typo':   'LeKoala\Base\Dev\TypographyController'
SilverStripe\Dev\DevBuildController:
  extensions:
    - LeKoala\Base\Dev\Extensions\DevBuildExtension
# TODO : move this to fake record generator
SilverStripe\Security\Group:
  extensions:
    - LeKoala\Base\Dev\Extensions\DevGroupExtension
SilverStripe\Core\Injector\Injector:
  SilverStripe\Dev\DebugView:
    class: LeKoala\Base\Dev\BetterDebugView
---
Name: base-dev-all
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Dev\MigrationTask:
    class: LeKoala\Base\Dev\Tasks\DisabledMigrationTasks
