---
Name: base-security
---
SilverStripe\Security\Security:
  login_recording: true
SilverStripe\Admin\SecurityAdmin:
  extensions:
    - LeKoala\Base\Security\BaseSecurityAdminExtension
SilverStripe\Security\Member:
  extensions:
    - LeKoala\Base\Security\BaseMemberExtension
LeKoala\Base\Security\MemberAudit:
  extensions:
    - LeKoala\Base\Extensions\IPExtension
# Prevent any destructive operation and safely migrate
SilverStripe\Assets\FileMigrationHelper:
  delete_invalid_files: false
