---
Name: base-security
---
# Global settings
SilverStripe\Security\Security:
  login_recording: true
# Extensions
SilverStripe\Admin\SecurityAdmin:
  extensions:
    - LeKoala\Base\Security\BaseSecurityAdminExtension
SilverStripe\Security\Member:
  extensions:
    - LeKoala\Base\Security\BaseMemberExtension
LeKoala\Base\Security\MemberAudit:
  extensions:
    - LeKoala\Base\Extensions\IPExtension
# Prevent any destructive operation and safely migrate
SilverStripe\Assets\FileMigrationHelper:
  delete_invalid_files: false
# Extensions for login/logout actions
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\MemberAuthenticator\MemberLoginForm:
    class: 'LeKoala\Base\Security\MemberLoginForm'
SilverStripe\Security\MemberAuthenticator\LoginHandler:
  extensions:
    - LeKoala\Base\Security\LoginHandlerExtension
SilverStripe\Security\MemberAuthenticator\LogoutHandler:
  extensions:
    - LeKoala\Base\Security\LogoutHandlerExtension
SilverStripe\Security\MemberAuthenticator\LostPasswordHandler:
  extensions:
    - LeKoala\Base\Security\LostPasswordHandlerExtension
